### PR TITLE
Updated README.md with setting up locales and adding user

### PR DESCRIPTION
**Pull request by Marin-Kitagawa**
Updated README.md with setting up locales and adding user and configuring default user as per Gentoo WSL instructions [Gentoo in WSL](https://wiki.gentoo.org/wiki/Gentoo_in_WSL)

### CODE REVIEW

**Comment by VPraharsha03** [comment]
Thanks for contributing! Will soon merge the PR

**Comment by Marin-Kitagawa** [comment]
Sure. Note the recent changes too. And thanks a lot for this.

**Comment by VPraharsha03** [comment]
> Sure. Note the recent changes too. And thanks a lot for this.

@ruby-rust-perl Ok sure, noted. You're welcome and please do give it a star⭐if you liked it!

**Comment by VPraharsha03** [comment]
Done.

**Pull request closed without merging**
